package unit.mapping;

import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class LocalDisplayMapper {
  private static final Map<String, String> mappings = generateMappings();

  private LocalDisplayMapper() {}

  public static Optional<String> fromLocalCode(String localCode) {
    return Optional.ofNullable(mappings.get(localCode));
  }

  public static Map<String, String> generateMappings() {
    var mappings = new HashMap<String, String>();
    mappings.put("10001", "Natrium.Li-Heparin .indirekte ISE");
    mappings.put("10002", "Kalium.Li-Heparin .indirekte ISE");
    mappings.put("10003", "Calcium.Li-Heparin .photometrisch");
    mappings.put("10004", "Magnesium.Li-Heparin .photometrisch");
    mappings.put("10005", "Chlorid.Li-Heparin .indirekte ISE");
    mappings.put("10007", "Phosphat anorganisch.Li-Heparin .photometrisch");
    mappings.put("10008", "Harnstoff.Li-Heparin .photometrisch");
    mappings.put("10009", "Kreatinin.Li-Heparin .Mod. Jaffe, kinetisch");
    mappings.put("10010", "Harnsäure.Li-Heparin .photometrisch");
    mappings.put("10011", "Glucose.Li-Heparin .Hexokinase");
    mappings.put("10012", "Bilirubin gesamt.Li-Heparin .photometrisch");
    mappings.put("10013", "Bilirubin direkt.Li-Heparin .photometrisch");
    mappings.put("10015", "Cholinesterase.Li-Heparin .photometrisch");
    mappings.put("10018", "AST.Li-Heparin .photometrisch");
    mappings.put("10019", "ALT.Li-Heparin .photometrisch");
    mappings.put("10020", "GGT.Li-Heparin .photometrisch");
    mappings.put("10021", "CK.Li-Heparin .photometrisch");
    mappings.put("10022", "LDH.Li-Heparin .photometrisch");
    mappings.put("10023", "CK-MB (Masse).Li-Heparin .ECLIA");
    mappings.put("10024", "GLDH.Li-Heparin .photometrisch");
    mappings.put("10025", "Eisen.Li-Heparin .photometrisch");
    mappings.put("10026", "Alkalische Phosphatase.Li-Heparin .photometrisch");
    mappings.put("10027", "Lipase.Li-Heparin .photometrisch");
    mappings.put("10028", "Ferritin.Li-Heparin .Turbidimetrie");
    mappings.put("10029", "Amylase.Li-Heparin .photometrisch");
    mappings.put("10030", "LDL-Cholesterin (Direktmessung).Li-Heparin .photometrisch");
    mappings.put("10031", "HDL-Cholesterin.Li-Heparin .photometrisch");
    mappings.put("10032", "Cholesterin.Li-Heparin .photometrisch");
    mappings.put("10033", "Triglyceride.Li-Heparin .photometrisch");
    mappings.put("10034", "Protein.Li-Heparin .photometrisch");
    mappings.put("10035", "Albumin.Li-Heparin .photometrisch");
    mappings.put("10036", "Freies Hämoglobin * **.Li-Heparin .photometrisch");
    mappings.put("10037", "C-reaktives Protein.Li-Heparin .Turbidimetrie-Latex");
    mappings.put("10038", "LDL-Chol. (Friedewald-Formel).Li-Heparin .berechnet");
    mappings.put("10039", "Dibucainzahl.Li-Heparin .berechnet");
    mappings.put("10041", "Myoglobin.Li-Heparin .Turbidimetrie");
    mappings.put("10042", "Troponin T.Li-Heparin .ECLIA");
    mappings.put("10043", "Cystatin-C.Li-Heparin .Turbidimetrie");
    mappings.put("10044", "Haptoglobin.Li-Heparin .Turbidimetrie");
    mappings.put("10045", "IgA.Li-Heparin .Turbidimetrie");
    mappings.put("10046", "IgG.Li-Heparin .Turbidimetrie");
    mappings.put("10047", "IgM.Li-Heparin .Turbidimetrie");
    mappings.put("10048", "Komplement C3c.Li-Heparin .Turbidimetrie");
    mappings.put("10049", "Komplement C4.Li-Heparin .Turbidimetrie");
    mappings.put("10050", "Löslicher Transferrin-Rezeptor.Li-Heparin .Turbidimetrie");
    mappings.put("10051", "Transferrin.Li-Heparin .Turbidimetrie");
    mappings.put("10052", "HBs-Antigen.Li-Heparin .ECLIA");
    mappings.put("10053", "HBs-Antigen.Serum .ECLIA");
    mappings.put("10054", "Procalcitonin (Roche).Li-Heparin .ECLIA");
    mappings.put("10056", "Alpha1-Antitrypsin.Li-Heparin .Turbidimetrie");
    mappings.put("10057", "Antistreptolysin O.Li-Heparin .Turbidimetrie");
    mappings.put("10058", "Apolipoprotein A1.Li-Heparin .Turbidimetrie");
    mappings.put("10059", "Apolipoprotein B.Li-Heparin .Turbidimetrie");
    mappings.put("10060", "Coeruloplasmin.Li-Heparin .Turbidimetrie");
    mappings.put("10061", "Lipoprotein (a).Li-Heparin .Turbidimetrie");
    mappings.put("10062", "Präalbumin.Li-Heparin .Turbidimetrie");
    mappings.put("10063", "Rheumafaktor.Li-Heparin .Turbidimetrie");
    mappings.put("10064", "ß2-Mikroglobulin.Li-Heparin .Turbidimetrie");
    mappings.put("10100", "Lithium.Serum .photometrisch");
    mappings.put("10101", "Protein.Serum .photometrisch");
    mappings.put("10151", "Ammoniak.EDTA (z) .photometrisch");
    mappings.put("10152", "Carbamazepin.Li-Heparin .Turbidimetrie");
    mappings.put("10153", "Digoxin.Li-Heparin .Turbidimetrie");
    mappings.put("10154", "Paracetamol.Li-Heparin .photometrisch");
    mappings.put("10155", "Phenobarbital.Li-Heparin .Turbidimetrie");
    mappings.put("10156", "Phenytoin.Li-Heparin .Turbidimetrie");
    mappings.put("10157", "Theophyllin.Li-Heparin .Turbidimetrie");
    mappings.put("10158", "Valproinsäure.Li-Heparin .EIA");
    mappings.put("10159", "Gentamicin.Li-Heparin .CEDIA");
    mappings.put("10160", "Vancomycin.Li-Heparin .EIA");
    mappings.put("10161", "Tacrolimus (LCMS)*.EDTA (NZ) .LCMS");
    mappings.put("10162", "Tacrolimus (EIA) *.EDTA-TACR .EIA");
    mappings.put("10163", "Sirolimus (Rapamycin)*.EDTA (NZ) .LCMS");
    mappings.put("10164", "Certican® (Everolimus) *.EDTA (NZ) .LCMS");
    mappings.put("10165", "Cyclosporin A Talspiegel (EIA) *.EDTA-CSA .CEDIA");
    mappings.put("10167", "Salicylat.Li-Heparin .photometrisch");
    mappings.put("10168", "Cyclosporin A Talspiegel (LCMS)*.EDTA (NZ) .LCMS");
    mappings.put("10171", "Amikacin.Li-Heparin .Turbidimetrie");
    mappings.put("10262", "Glucose.Na-Fluorid .Hexokinase");
    mappings.put("10263", "Glucose.Na-Fluorid .Hexokinase");
    mappings.put("10523", "Calcium Konzentration.SpUrin(z) .photometrisch");
    mappings.put("10525", "Phosphat Konzentration.SpUrin(z) .photometrisch");
    mappings.put("10526", "Kreatinin Konzentration.SpUrin(z) .Mod. Jaffe, kinetisch");
    mappings.put("10527", "Natrium bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("10528", "Kalium bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("10530", "Chloridkonz. bez.auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("10551", "Natrium Ausscheidung.Sammelurin .berechnet");
    mappings.put("10553", "Kalium Ausscheidung.Sammelurin .berechnet");
    mappings.put("10555", "Calcium Ausscheidung.Sammelurin .berechnet");
    mappings.put("10557", "Chlorid Ausscheidung.Sammelurin .berechnet");
    mappings.put("10559", "Phosphat Ausscheidung.Sammelurin .berechnet");
    mappings.put("10560", "Phosphatclearance.Sammelurin .berechnet");
    mappings.put("10561", "Phosphat (Plasma) z. Berechnung. .");
    mappings.put("10562", "Glucose Konzentration.Sammelurin .Hexokinase");
    mappings.put("10563", "Glucose Ausscheidung.Sammelurin .berechnet");
    mappings.put("10565", "Harnstoff Ausscheidung.Sammelurin .berechnet");
    mappings.put("10567", "Harnsäure Ausscheidung.Sammelurin .berechnet");
    mappings.put("10569", "Kreatinin Ausscheidung.Sammelurin .berechnet");
    mappings.put("10572", "Kreatinin im Plasma.BELLA .Mod. Jaffe, kinetisch");
    mappings.put("10579", "Magnesium Konzentration.Sammelurin .photometrisch");
    mappings.put("10580", "Magnesium Ausscheidung.Sammelurin .berechnet");
    mappings.put("10588", "Protein Konzentration.SpUrin(z) .photometrisch");
    mappings.put("10619", "Protein Konzentration.Sammelurin .photometrisch");
    mappings.put("10620", "Protein Ausscheidung.Sammelurin .berechnet");
    mappings.put("10621", "Proteinkonz. bez. auf Kreatinin.Sammelurin .berechnet");
    mappings.put("10622", "Protein/mol Kreatinin.SpUrin(z) .berechnet");
    mappings.put("10623", "Protein/g Kreatinin.SpUrin(z) .berechnet");
    mappings.put("1070", "Leukozyten.Liquor .optisch, Lasertechnol.");
    mappings.put("1071", "Zellen kernhaltig.Liquor .optisch, Lasertechnol.");
    mappings.put("1072", "Erythrozyten.Liquor .optisch, Lasertechnol.");
    mappings.put("1073", "Polymorphnukleäre Zellen relativ.Liquor .optisch, Lasertechnol.");
    mappings.put("1074", "Polymorphnukleäre Zellen absolut.Liquor .optisch, Lasertechnol.");
    mappings.put("1075", "Mononukleäre Zellen relativ.Liquor .optisch, Lasertechnol.");
    mappings.put("10750", "Protein.Liquor .Turbidimetrie");
    mappings.put("10751", "Glucose.Liquor .Hexokinase");
    mappings.put("10752", "Lactat.Liquor .photometrisch");
    mappings.put("10753", "LDH**.Liquor .photometrisch");
    mappings.put("10754", "Albumin #.Liquor .photometrisch");
    mappings.put("1076", "Mononukleäre Zellen absolut.Liquor .optisch, Lasertechnol.");
    mappings.put("1121", "Segmentkernige relativ.EDTA .");
    mappings.put("1123", "Eosinophile relativ.EDTA .");
    mappings.put("1124", "Basophile relativ.EDTA .");
    mappings.put("1125", "Lymphozyten relativ.EDTA .");
    mappings.put("1126", "Monozyten relativ.EDTA .");
    mappings.put("1142", "Reticulozyten relativ.EDTA .");
    mappings.put("117", "Alpha1 saures Glycoprotein.Li-Heparin .Nephelometrie");
    mappings.put("118", "Alpha2 Makroglobulin.Li-Heparin .Nephelometrie");
    mappings.put("127", "Interleukin 8.Li-Heparin .CLIA");
    mappings.put("133", "Freie Kappa-Leichtketten.Serum .Nephelometrie");
    mappings.put("134", "Freie Lambda-Leichtketten.Serum .Nephelometrie");
    mappings.put("135", "Quotient freie Kappa/Lambda-LK.Serum .berechnet");
    mappings.put("139", "Mycophenolsäure HPLC.EDTA (z) .HPLC");
    mappings.put("142", "Vitamin B1.EDTA .HPLC");
    mappings.put("144", "Vitamin B6.EDTA (NZ) .HPLC");
    mappings.put("159", "HbA1c (NGSP-Standardisierung).EDTA (NZ) .HPLC");
    mappings.put("182", "IgG.Serum .Nephelometrie");
    mappings.put("212", "Digitoxin.Li-Heparin .ECLIA");
    mappings.put("230", "Methämoglobin.EDTA (NZ) .photometrisch");
    mappings.put("231", "CO-Hb.EDTA (NZ) .photometrisch");
    mappings.put("233", "IgG 1 Subklasse.Serum .Nephelometrie");
    mappings.put("234", "IgG 2 Subklasse.Serum .Nephelometrie");
    mappings.put("235", "IgG 3 Subklasse.Serum .Nephelometrie");
    mappings.put("236", "IgG 4 Subklasse.Serum .Nephelometrie");
    mappings.put("237", "Insulin.Serum .CLIA");
    mappings.put("238", "Proinsulin.Serum .EIA");
    mappings.put("239", "Wachstumshormon (HGH).Serum .CLIA");
    mappings.put("284", "Albumin relativ.Serum .Elektrophorese");
    mappings.put("286", "Alpha1-Globulin relativ.Serum .Elektrophorese");
    mappings.put("288", "Alpha2-Globulin relativ.Serum .Elektrophorese");
    mappings.put("290", "Beta-Globulin relativ.Serum .Elektrophorese");
    mappings.put("292", "Gamma-Globulin relativ.Serum .Elektrophorese");
    mappings.put("298", "Reticulozyten relativ.EDTA .berechnet");
    mappings.put("299", "Reticulozyten absolut.EDTA .optisch, Lasertechnol.");
    mappings.put("301", "pH.BGA .Potentiometrie");
    mappings.put("302", "pCO2.BGA .Potentiometrie");
    mappings.put("303", "pO2.BGA .Amperometrie");
    mappings.put("304", "Bicarbonat.BGA .berechnet");
    mappings.put("305", "Basenabweichung.BGA .berechnet");
    mappings.put("306", "Methämoglobin.BGA .photometrisch");
    mappings.put("307", "CO-Hb.BGA .photometrisch");
    mappings.put("308", "Hämoglobin.BGA .photometrisch");
    mappings.put("311", "PTT Hepzyme.Citrat .Turbidimetrie");
    mappings.put("315", "Quick.Citrat .Turbidimetrie");
    mappings.put("316", "PTT.Citrat .Turbidimetrie");
    mappings.put("318", "Fibrinogen.Citrat .Turbidimetrie");
    mappings.put("331", "Erythrozyten.EDTA .Widerstandsmessung");
    mappings.put("332", "Leukozyten.EDTA .optisch, Lasertechnol.");
    mappings.put("333", "Hämoglobin.EDTA .photometrisch");
    mappings.put("334", "Hämatokrit.EDTA .berechnet");
    mappings.put("335", "MCH.EDTA .berechnet");
    mappings.put("336", "MCHC.EDTA .berechnet");
    mappings.put("337", "MCV.EDTA .Widerstandsmessung");
    mappings.put("338", "Thrombozyten.EDTA .Widerstandsmessung");
    mappings.put("339", "Lymphozyten absolut.EDTA .berechnet");
    mappings.put("340", "Lymphozyten relativ.EDTA .optisch, Lasertechnol.");
    mappings.put("341", "neutrophile Granulozyten absolut.EDTA .berechnet");
    mappings.put("342", "neutrophile Granulozyten relativ.EDTA .optisch, Lasertechnol.");
    mappings.put("344", "Basophile absolut.EDTA .berechnet");
    mappings.put("345", "Basophile relativ.EDTA .optisch, Lasertechnol.");
    mappings.put("346", "Eosinophile absolut.EDTA .berechnet");
    mappings.put("347", "Eosinophile relativ.EDTA .optisch, Lasertechnol.");
    mappings.put("348", "Monozyten absolut.EDTA .berechnet");
    mappings.put("349", "Monozyten relativ.EDTA .optisch, Lasertechnol.");
    mappings.put("351", "Hämatokrit zentrifugiert.EDTA .zentrifugiert");
    mappings.put("356", "Thrombozyten Kammerzählung.EDTA .Mikroskopie");
    mappings.put("361", "Chlorid.Sondermaterial .Coulometrie");
    mappings.put("370", "Glucose.Sondermaterial .Glucose-Oxidase");
    mappings.put("374", "Protein C Antigen.Citrat .EIA");
    mappings.put("385", "TAT-K (Thrombin/Antithrombinkom).Citrat .");
    mappings.put("388", "Protein S Antigen gesamt.Citrat .EIA");
    mappings.put("403", "Glucose Tagesprofil 7.30 Uhr.BZ 07:30 .Glucose-Oxidase");
    mappings.put("424", "ACHE Elektrophorese.Fruchtwasser .Elektrophorese");
    mappings.put("438", "Fibrinogen nach Schulz.Citrat .Hitzefällung");
    mappings.put("454", "Eosinophile relativ.EDTA .");
    mappings.put("455", "Basophile relativ.EDTA .");
    mappings.put("456", "Lymphozyten relativ.EDTA .");
    mappings.put("457", "Monozyten relativ.EDTA .");
    mappings.put("47", "Eisensättigung.Li-Heparin .berechnet");
    mappings.put("499", "MTV.EDTA .Widerstandsmessung");
    mappings.put("501", "pH.Spontanurin .Teststreifen");
    mappings.put("504", "Leukozyten.Spontanurin .Teststreifen");
    mappings.put("505", "Glucose.Spontanurin .Teststreifen");
    mappings.put("506", "Keton.Spontanurin .Teststreifen");
    mappings.put("507", "Urobilinogen.Spontanurin .Teststreifen");
    mappings.put("508", "Nitrit.Spontanurin .Teststreifen");
    mappings.put("509", "Nitrit.Sammelurin .Teststreifen");
    mappings.put("513", "Bakterien.Spontanurin .Mikroskopie");
    mappings.put("519", "Glucose/Teststreifen.Sammelurin .Teststreifen");
    mappings.put("53", "NT-proBNP.Li-Heparin .ECLIA");
    mappings.put("5301", "Glucose.Sondermaterial .Glucose-Oxidase");
    mappings.put("5307", "HGH.Serum .CLIA");
    mappings.put("5311", "Proinsulin.Serum .EIA");
    mappings.put("5315", "Calcitonin.Serum .CLIA");
    mappings.put("5321", "TSH.Serum .ECLIA");
    mappings.put("5322", "Follikel stim. Hormon (FSH).Serum .ECLIA");
    mappings.put("5323", "Luteinisierendes Hormon (LH).Serum .ECLIA");
    mappings.put("5324", "Insulin.Serum .ECLIA");
    mappings.put("5325", "C-Peptid.Serum .");
    mappings.put("5326", "Cortisol.Serum .ECLIA");
    mappings.put("5329", "DHEA-Sulfat.Serum .ECLIA");
    mappings.put("533", "Albumin Konzentration.SpUrin(z) .Nephelometrie");
    mappings.put("5332", "Prolactin.Serum .ECLIA");
    mappings.put("5334", "Androstendion.Serum .CLIA");
    mappings.put("5335", "DHEA *.Serum .RIA");
    mappings.put("5336", "17alpha-Hydroxyprogesteron.Serum .ELISA");
    mappings.put("5339", "unreife Thrombozytenfraktion.EDTA .optisch, Lasertechnol.");
    mappings.put("534", "Albuminkonz. bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("5340", "unreife Retikulozytenfraktion.EDTA .optisch, Lasertechnol.");
    mappings.put("5341", "Hb-Gehalt Retikulozyten.EDTA .optisch, Lasertechnol.");
    mappings.put("5344", "Posaconazol.EDTA (z) .HPLC");
    mappings.put("5346", "Oestronsulfat.Serum .RIA");
    mappings.put("5348", "Protein S Antigen frei.Citrat .photometrisch");
    mappings.put("535", "IgG Konzentration.SpUrin(z) .Nephelometrie");
    mappings.put("536", "IgG-Konz. bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("537", "A1-Mikroglobulin.SpUrin(z) .Nephelometrie");
    mappings.put("5370", "Intem Clotformation Time.CitratVB .TEG");
    mappings.put("5374", "Heptem Clottingtime.CitratVB .TEG");
    mappings.put("5375", "Heptem Clotformation Time.CitratVB .TEG");
    mappings.put("5377", "Fibtem Maximal Clotfirmnes.CitratVB .TEG");
    mappings.put("538", "Alpha1Mikroglob. bez. auf Krea..SpUrin(z) .berechnet");
    mappings.put("5384", "Testosteron.Serum .ECLIA");
    mappings.put("5385", "Interleukin 6.Li-Heparin .ECLIA");
    mappings.put("5389", "Tricyclische Antidepressiva.Spontanurin .Chromatographie");
    mappings.put("539", "A2-Makroglobulin.SpUrin(z) .Nephelometrie");
    mappings.put("5395", "GammaGlobulin relativ.Sammelurin .Elektrophorese");
    mappings.put("540", "Kappa Leichtketten Konzentration.SpUrin(z) .Nephelometrie");
    mappings.put("5400", "c-ANCA (PR3).Serum .FEIA");
    mappings.put("5401", "p-ANCA (MPO).Serum .FEIA");
    mappings.put("5402", "Cardiolipin AK IgM.Serum .FEIA");
    mappings.put("5403", "Cardiolipin AK IgG.Serum .FEIA");
    mappings.put("5404", "B2-Glycoprotein AK IgM.Serum .FEIA");
    mappings.put("5405", "B2-Glycoprotein AK IgG.Serum .FEIA");
    mappings.put("5406", "cycl. citrullierendes Peptid AK.Serum .FEIA");
    mappings.put("5408", "Scl-70-AK.Serum .FEIA");
    mappings.put("5409", "SM-AK (SmD-AK).Serum .FEIA");
    mappings.put("541", "Lambda Leichtketten Konzentr..SpUrin(z) .Nephelometrie");
    mappings.put("5410", "SSA-RO-AK (60/52 kDa).Serum .FEIA");
    mappings.put("5411", "SSB-LA-AK.Serum .FEIA");
    mappings.put("5412", "U1 RNP-AK (RNP70kDA,RNP-A,RNP-C).Serum .FEIA");
    mappings.put("5413", "Jo-1-AK.Serum .FEIA");
    mappings.put("5414", "Centromer-AK (CENP-B).Serum .FEIA");
    mappings.put("5415", "Antinukleäre-AK IFT-Titer*.Serum .FEIA");
    mappings.put("5418", "Neopterin.Serum .ELISA");
    mappings.put("5419", "ds-DNA-AK.Serum .FEIA");
    mappings.put("542", "Kappa/Lambda-Quotient.SpUrin(z) .berechnet");
    mappings.put("5420", "Eosinophil Cationic Protein(ECP).Serum .FEIA");
    mappings.put("5421", "IgE/p2-Echinococcus.Serum .FEIA");
    mappings.put("5422", "glomeruläre Basalmembran-AK.Serum .FEIA");
    mappings.put("5425", "Troponin T STAT.Li-Heparin .");
    mappings.put("5427", "freies Testosteron quantitativ.Serum .berechnet");
    mappings.put("5431", "HLA B*5701.EDTA .PCR");
    mappings.put("5433", "HbA1c (IFCC-Standardisierung).EDTA (NZ) .HPLC");
    mappings.put("5434", "SCC (IBL).Serum .EIA");
    mappings.put("5435", "Testosteron.Serum .ECLIA");
    mappings.put("5441", "Quotient PSA frei/gesamt.Serum .berechnet");
    mappings.put("5444", "IGF-1 (DPC).Serum .CLIA");
    mappings.put("5445", "Voriconazol.EDTA (z) .HPLC");
    mappings.put("545", "Benzodiazepine.Spontanurin .Immunchromatographie");
    mappings.put("5461", "Faktor VIII-Aktivität.Citrat .Clotting");
    mappings.put("5462", "Faktor IX-Aktivität.Citrat .Clotting");
    mappings.put("5463", "Faktor II.Citrat .Clotting");
    mappings.put("5464", "Faktor V.Citrat .Clotting");
    mappings.put("5465", "Faktor VII.Citrat .Clotting");
    mappings.put("5466", "Faktor X.Citrat .Clotting");
    mappings.put("5467", "Faktor XI.Citrat .Clotting");
    mappings.put("5468", "Faktor XII.Citrat .Clotting");
    mappings.put("5469", "Faktor XIII.Citrat .Clotting");
    mappings.put("5470", "von Willebrand Antigen.Citrat .Turbidimetrie");
    mappings.put("5471", "Ristocetin Kofaktor.Citrat .Turbidimetrie");
    mappings.put("5472", "Faktor VIII Inhibitor **.Citrat .berechnet");
    mappings.put("5477", "Epinephrin.PFA .Verschlußzeit");
    mappings.put("5478", "ADP.PFA .Verschlußzeit");
    mappings.put("549", "Osmolalität.SpUrin(z) .Gefrierpkterniedriegung");
    mappings.put("5503", "Plasminogen.Citrat .chromogen");
    mappings.put("5504", "Tissue Plasminogen Aktivator.Citrat .ELISA");
    mappings.put("5505", "Alpha 2 Antiplasmin.Citrat .chromogen");
    mappings.put("5506", "VWF Kollagenbindungsaktivität.Citrat .ELISA");
    mappings.put("5507", "von Willebrand:CB/AG-Quotient.Citrat .berechnet");
    mappings.put("5508", "von Willebrand:RCo/AG-Quotient.Citrat .berechnet");
    mappings.put("5509", "FVIII/von Willebrand:AG-Quotient.Citrat .berechnet");
    mappings.put("5512", "PAI.Citrat .chromogen");
    mappings.put("5513", "Prothrombinfragment F 1+2.Citrat .");
    mappings.put("578", "Kupfer Ausscheidung.Sammelurin .berechnet");
    mappings.put("581", "Osmolalität.Sammelurin .Gefrierpkterniedriegung");
    mappings.put("583", "Amphetamin-Screening.Spontanurin .Immunchromatographie");
    mappings.put("586", "Opiat-Screening.Spontanurin .Immunchromatographie");
    mappings.put("587", "Leukozyten/Teststreifen.Sammelurin .Teststreifen");
    mappings.put("594", "Albumin Konzentration.Sammelurin .Nephelometrie");
    mappings.put("595", "Albumin Ausscheidung.Sammelurin .berechnet");
    mappings.put("596", "Albuminkonz. bez. auf Kreatinin.Sammelurin .berechnet");
    mappings.put("597", "IgG Konzentration.Sammelurin .Nephelometrie");
    mappings.put("598", "IgG Ausscheidung.Sammelurin .berechnet");
    mappings.put("599", "IgG bez. auf Kreatinin.Sammelurin .berechnet");
    mappings.put("6", "Osmolalität.Li-Heparin .Gefrierpkterniedriegung");
    mappings.put("600", "A1-Mikroglobulin.Sammelurin .Nephelometrie");
    mappings.put("601", "A1M-Ausscheidung.Sammelurin .berechnet");
    mappings.put("602", "Alpha1Mikroglob. bez. auf Krea..Sammelurin .berechnet");
    mappings.put("603", "A2-Makroglobulin.Sammelurin .Nephelometrie");
    mappings.put("604", "Kappa Leichtketten Konzentration.Sammelurin .Nephelometrie");
    mappings.put("605", "Lambda Leichtketten Konzentr..Sammelurin .Nephelometrie");
    mappings.put("606", "Kappa/Lambda-Quotient.Sammelurin .berechnet");
    mappings.put("610", "DeltaAminolävulinsäure Aussch..Sammelurin .berechnet");
    mappings.put("612", "Porphyrine gesamt Ausscheidung.Sammelurin .berechnet");
    mappings.put("614", "Porphobilinogen Ausscheidung.Sammelurin .berechnet");
    mappings.put("625", "freies Cortisol/Tag.Sammelurin .berechnet");
    mappings.put("626", "Albumin/Minute.Sammelurin .berechnet");
    mappings.put("631", "Albumin.Liquor .photometrisch");
    mappings.put("632", "IgG.Liquor .Nephelometrie");
    mappings.put("640", "Adrenalin Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("642", "Noradrenalin Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("644", "Dopamin Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("646", "Vanillinmandelsäure Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("648", "Homovanillinsäure Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("650", "Metanephrin Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("652", "Normetanephrin Ausscheidung.Sammelurin sauer.berechnet");
    mappings.put("654", "5-Hydroxyindolessigsäure Aussch..Sammelurin sauer.berechnet");
    mappings.put("658", "Adrenalin bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("660", "Noradrenalin bez. a. Kreatinin.SpUrin(z) .berechnet");
    mappings.put("662", "Dopamin bez. auf Kreatinin.SpUrin(z) .berechnet");
    mappings.put("664", "Vanillinmandelsre. bez. a. Krea..SpUrin(z) .berechnet");
    mappings.put("666", "Homovanillinsre. bez. a. Krea..SpUrin(z) .berechnet");
    mappings.put("686", "Bakterien.Sondermaterial .");
    mappings.put("695", "Bakterien.Liquor .");
    mappings.put("696", "Erythrozyten.Liquor .");
    mappings.put("762", "Leukozyten.Spontanurin .");
    mappings.put("763", "Erythrozyten.Spontanurin .");
    mappings.put("764", "Bakterien.Spontanurin .");
    mappings.put("775", "Kreatininclear. bez.a. Körperob..Sammelurin .berechnet");
    mappings.put("778", "freies Cortisol Ausscheidung.Sammelurin .berechnet");
    mappings.put("779", "Protein (vorwiegend Albumin).Spontanurin .Teststreifen");
    mappings.put("781", "Bilirubin.Spontanurin .Teststreifen");
    mappings.put("782", "Protein (vorwiegend Albumin).Sammelurin .Teststreifen");
    mappings.put("786", "Itraconazol.EDTA (z) .HPLC");
    mappings.put("788", "Itraconazol+Hydroxy-Itraconazol.EDTA (z) .HPLC");
    mappings.put("790", "Gesamtmetanephrin bez. auf Krea..SpUrin(z) .berechnet");
    mappings.put("793", "Parathormon.EDTA (z) .CLIA");
    mappings.put("806", "Tg-Wiederfindung.Serum .berechnet");
    mappings.put("807", "Thyreoglobulin.Serum .CLIA");
    mappings.put("809", "TSH-Rezeptor Antikörper (TRAK).Serum .CLIA");
    mappings.put("811", "Thyreoperoxidase-Antikörp.,Roche.Serum .ECLIA");
    mappings.put("841", "Gesamt T3.Serum .ECLIA");
    mappings.put("842", "Freies T3.Serum .ECLIA");
    mappings.put("843", "Gesamt T4.Serum .ECLIA");
    mappings.put("844", "Freies T4.Serum .ECLIA");
    mappings.put("845", "TSH.Serum .ECLIA");
    mappings.put("846", "HCG + ß-HCG (Roche).Serum .ECLIA");
    mappings.put("847", "Oestradiol.Serum .ECLIA");
    mappings.put("848", "Follikel stim. Hormon (FSH).Serum .ECLIA");
    mappings.put("849", "Luteinisierendes Hormon (LH).Serum .ECLIA");
    mappings.put("850", "Progesteron.Serum .ECLIA");
    mappings.put("855", "Cortisol.Serum .ECLIA");
    mappings.put("856", "Dehydroepiandrosteron-Sulfat.Serum .ECLIA");
    mappings.put("857", "Sex Hormone-binding Globulin.Serum .ECLIA");
    mappings.put("858", "Alpha-Fetoprotein (Fa.Roche).Serum .ECLIA");
    mappings.put("859", "CA 15-3 (Fa.Roche).Serum .ECLIA");
    mappings.put("860", "CA 19-9 (Fa.Roche).Serum .ECLIA");
    mappings.put("861", "CA 125-II (Fa.Roche).Serum .ECLIA");
    mappings.put("864", "Folsäure.Serum .ECLIA");
    mappings.put("865", "IgE.Serum .ECLIA");
    mappings.put("867", "HCG + ß-HCG (Fa. Roche).Serum .ECLIA");
    mappings.put("868", "S100 (A1B+BB) (Fa. Roche).Serum .ECLIA");
    mappings.put("870", "N-MID-Osteocalcin.Serum .ECLIA");
    mappings.put("871", "Prokollagen-Typ-1-AT-Peptid.Serum .ECLIA");
    mappings.put("872", "ß-Crosslaps.Serum .ECLIA");
    mappings.put("873", "Prolactin.Serum .ECLIA");
    mappings.put("874", "IGF-1 (DPC).Serum .CLIA");
    mappings.put("875", "IGFBP-3 (DPC).Serum .CLIA");
    mappings.put("876", "APC-Resistenz.Citrat .photometrisch");
    mappings.put("882", "PSA hochsensitiv (Fa. Roche).Serum .ECLIA");
    mappings.put("885", "Kaolinzeit.Citrat .Turbidimetrie");
    mappings.put("888", "Rosner-Index.Citrat .berechnet");
    mappings.put("894", "Antithrombin 3.Citrat .photometrisch");
    mappings.put("895", "Calcitonin.Serum .CLIA");
    mappings.put("896", "Homocystein.EDTA (z) .CLIA");
    mappings.put("897", "Vitamin B12.Serum .ECLIA");
    mappings.put("898", "CDT.Serum .berechnet");
    mappings.put("900", "Transferrin abs. für CDT.Serum .Nephelometrie");
    mappings.put("909", "Androstendion.Serum .CLIA");
    mappings.put("910", "Dehydroepiandrosteron *.Serum .RIA");
    mappings.put("911", "Kalium im Vollblut.BGA .ISE direkt");
    mappings.put("912", "Glucose im Vollblut.BGA .Glucose-Oxidase");
    mappings.put("913", "Ionisiertes Calcium.BGA .ISE direkt");
    mappings.put("914", "Ionisiertes Calcium (pH 7.4).BGA .berechnet");
    mappings.put("917", "Sauerstoff-Sättigung.BGA .photometrisch");
    mappings.put("921", "Parathormon intraoperativ DPC.EDTA (z) .CLIA");
    mappings.put("924", "Thrombinzeit.Citrat .Turbidimetrie");
    mappings.put("925", "Thrombozyten.Sondermaterial .Widerstandsmessung");
    mappings.put("93", "Insulin.Serum .ECLIA");
    mappings.put("936", "Zink.Li-Heparin .Atomabsorbtion");
    mappings.put("937", "Kupfer.Li-Heparin .Atomabsorbtion");
    mappings.put("938", "CEA (Fa.Roche).Serum .ECLIA");
    mappings.put("94", "C-Peptid.Serum .ECLIA");
    mappings.put("944", "BSG.EDTA .photometrisch");
    mappings.put("951", "AFP.Fruchtwasser .ECLIA");
    mappings.put("952", "AFP.Fruchtwasser .berechnet");
    mappings.put("955", "Leukozyten.Liquor .");
    mappings.put("956", "17alpha-Hydroxyprogesteron.Serum .ELISA");
    mappings.put("957", "17a.-OH-Progesteron extrahiert.Serum .ELISA");
    mappings.put("960", "Thyreoglobulin (Roche).Serum .ECLIA");
    mappings.put("961", "Tg-Wiederfindung (Roche).Serum .berechnet");
    mappings.put("971", "Erythrozyten.Spontanurin .optisch, Lasertechnol.");
    mappings.put("972", "Leukozyten.Spontanurin .optisch, Lasertechnol.");
    mappings.put("973", "Bakterien.Spontanurin .optisch, Lasertechnol.");
    mappings.put("974", "Zylinder.Spontanurin .optisch, Lasertechnol.");
    mappings.put("976", "Kristalle.Spontanurin .optisch, Lasertechnol.");
    mappings.put("977", "Rundepithelien.Spontanurin .optisch, Lasertechnol.");
    mappings.put("978", "pathologische Zylinder.Spontanurin .optisch, Lasertechnol.");
    mappings.put("979", "Hefezellen.Spontanurin .optisch, Lasertechnol.");
    mappings.put("980", "Spermien.Spontanurin .optisch, Lasertechnol.");
    mappings.put("983", "Orgaran® (Danaparoid-Na) anti Xa.Citrat .photometrisch");
    mappings.put("984", "D-Dimere.Citrat .Turbidimetrie-Latex");
    mappings.put("988", "Thyreoglobulin-Antikörper, Roche.Serum .ECLIA");
    mappings.put("993", "Erythropoietin.Serum .EIA");
    return mappings;
  }
}
